import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inconsolata, Inter, Lora } from "next/font/google";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });
const lora = Lora({ subsets: ["latin"] });
const incosolata = Inconsolata({ subsets: ["latin"] });
const font = inter.className;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
